apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-kubernetes-cluster
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 3
    minSize: 1
    maxSize: 4
